### ISSUE TITLE
你页面是怎么把它固定在手机板页面的阿

### ISSUE THREAD

**Issue by ms0391386** [chilliness/ngx-eleme#1]
你web页面是怎么把它固定在手机板页面的阿，我用电脑打开也是手机板页面，想知道

**Comment by chilliness** [comment]
本身就是移动端项目，使用的是flex布局，所以能够更好的适配设备。

**Comment by ms0391386** [comment]
我看不懂为什么你在组件里写了很多看起来像监听函数，像是handleInitScroll这个方法好像是监听DIV的，可以知道为什么要这样写吗?

**Comment by chilliness** [comment]
就是普通方法，个人的命名习惯罢了。
